### ISSUE TITLE
Starting from a symbolic link causes doomrl to be unable to find config.lua - Ubuntu 16.10

### ISSUE THREAD

**Issue by ryanford** [chaosforgeorg/doomrl#12]
From website download version 0.997 Works fine when running from original unzipped folder. If I create a symbolic link to doomrl in say /usr/bin or /usr/games, game is unable to find config.lua and crashes.

**Edit:** After playing around with it for a while, I think you can only call it from the parent directory with `./doomrl`. You can't call it with an absolute path name even. Right now, I've made a script to `cd /dir/to/doom/ && ./doomrl`  but surely there's some kind of relative paths in the code that's preventing normal function.

This is the error output:

```
xxxxxxxxxxxxxx:~$ /games/doomrl-linux-x64-0997/doomrl



Abnormal program termination!

Reason : cannot open config.lua: No such file or directory

If this reason doesn't seem your fault, please submit a bug report at
http://forum.chaosforge.org/, be sure to include the last entries in
your error.log that will get created once you hit Enter.

An unhandled exception occurred at $0000000000579E5C :
ELuaException : cannot open config.lua: No such file or directory
  $0000000000579E5C line 140 of ../fpcvalkyrie/src/vluaconfig.pas
  $0000000000579F71 line 149 of ../fpcvalkyrie/src/vluaconfig.pas
  $0000000000574BB4 line 107 of src/doomconfig.pas
  $000000000046BFA5 line 221 of src/doombase.pas
  $00000000004285FA line 86 of src/doomrl.pas

xxxxxxxxxxxxx:~$ 
```

Note that I'm calling the absolute path to the doomrl file. Same result if I try any kind of symbolic link or shell scripts to the absolute path.

**Comment by CyberKiller40** [comment]
Known issue for many years, I couldn't convince the author to change this behavior since like 5 years ago or more.

You can use a wrapper script, like this one I wrote, to run the game from other locations:
```
#!/bin/bash

# GNU/Linux launcher script, by Cyber Killer
# license: Public Domain

cd "`dirname $0`"
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64:/usr/lib:./lib ./programexec
```

**Comment by epyon** [comment]
I've changed the way that paths are treated on Linux with 0.9.9.8 BETA 1, is this issue still valid?
