### ISSUE TITLE
Barrel + teleporter glitch

### ISSUE THREAD

**Issue by GothBoiClick** [chaosforgeorg/doomrl#140]
Playing on 0.9.9.7 stable Linux version. I was curious if I could make monsters telefrag themselves by pushing a barrel into the teleporter's exit tile, but when a monster tried to teleport into it the in-game log said something about an error. I don't see it in the log.txt, but here's what the game put into error.log:

> Timestamp   : 9-8-24 12:42:34
> Error level : ERROR
> Message     : Lua hook OnAction caught EAccessViolation!
> 
> Call path     : beings[].OnAction
> Call params   : ()
> Error message : Access violation

**Comment by epyon** [comment]
This is reportedly fixed in 0.9.9.8.
