### ISSUE TITLE
Ingame Lightfoot Platinum Badge description is missing the UV requirement

### ISSUE THREAD

**Issue by Andrew-RK** [chaosforgeorg/doomrl#26]
In DoomRL 0.9.9.7, The ingame description for Lightfoot Platinum says "Complete AoLT under 20,000 turns". What it doesn't say is that in addition to completing Angel of Light Travel in less than 20,000 turns, you need to also be playing on Ultra Violence to get credit for the badge.

**Comment by epyon** [comment]
Fixed in BETA 1
