### ISSUE TITLE
Error: Can't determine which overloaded function to call

### ISSUE THREAD

**Issue by EndHack** [chaosforgeorg/doomrl#27]
So I've been trying to compile this on windows, and I followed the instructions number 4 where I got an error.

`vconui.pas(411,20)` Error: Can't determine which overloaded function to call`

I decided to skip this and just pull the wad files over from the game since I already had it downloaded, and I moved on and tried step 7 and got the same error.

This Min seems to be the problem, but I don't really know what to do here.

```procedure TConUIMenu.RecalcDimensions;
begin
  inherited RecalcDimensions;
  FVisibleCount := Min( Max(FCount, FVisibleCount), FAbsolute.h );
end;

**Comment by thechampion** [comment]
Try explicit type cast ti the typeof(FAbsolute.h).

**Comment by EndHack** [comment]
So in all honesty I don't know what that means, I don't actual know much about what I'm doing when it comes to most of this stuff. I'm really only trying to compile this so I can add some new tiles and enemies, since the modding doesn't support new tiles.

**Comment by thechampion** [comment]
Try to replace line 411 with

`FVisibleCount := Min( Max(FCount, FVisibleCount), DWord(FAbsolute.h) );`

and rebuild.

**Comment by EndHack** [comment]
Thanks that got me further, but I ran into more problems.

on line 1135 of dflevel.

`dflevel.pas(1135,17) Error: Procedure directive "VIRTUAL" cannot be used with "INLINE"`

```
function TLevel.getCell( const aWhere : TCoord2D ) : byte; inline;
var iOverlay : Word;
begin
  iOverlay := Map.d[aWhere.x, aWhere.y];
  if iOverlay <> 0 then Exit( iOverlay );
  Result := inherited GetCell( aWhere );
end;
```

and then it looks like there is another error on 1143.

`dflevel.pas(1143,18) Error: Procedure directive "VIRTUAL" cannot be used with "INLINE"`

```
procedure TLevel.putCell( const aWhere : TCoord2D; const aWhat : byte ); inline;
begin
  if CF_OVERLAY in Cells[ aWhat ].Flags
  then
     Map.d[aWhere.x, aWhere.y] := aWhat
  else
  begin
    inherited PutCell( aWhere, aWhat );
    Map.d[aWhere.x, aWhere.y] := 0;
  end;
end; 
```

**Comment by thechampion** [comment]
What Windows version and what compiler do you use?

**Comment by EndHack** [comment]
I'm using Windows 10 home, and I'm using Lazarus so I believe the compiler is FPC.

**Comment by epyon** [comment]
This is FPC 3.2.0 specifict - this has been fixed in the new development branch of git (also development branch of FPC Valkyrie).
