### ISSUE TITLE
[GNU/Linux] Unhandled Exception on startup

### ISSUE THREAD

**Issue by CaptainInfested** [chaosforgeorg/doomrl#29]
When trying to start `doomrl 0.9.9.7-11` under latest Artix Linux (uses AUR like Arch), I get the following error:
```
An unhandled exception occurred at $00000000005F4352 :
EInOutError : Invalid input
  $00000000005F4352
```

**Comment by epyon** [comment]
Unfortunately this is way too little to go on from, and I only now had the time to look on this. Please try the next release once it comes out and report if you still have issues then!
