### ISSUE TITLE
Inconsistent use of difficulty names

### ISSUE THREAD

**Issue by Wuzzy2** [chaosforgeorg/doomrl#34]
The game uses difficulty names a bit inconsistently.

Usually, it's names like "I'm Too Young to Die" but sometimes simple names like "Easy", "Medium", etc. are used. These are used e.g. in highscores and the "Show player" screen of the main menu.

It's not exactly obvious which name maps to which one. That's a little confusing.

I suggest to use one uniform set of difficulty names and stick with it throughout the game. Or maybe you can come up with a better idea.

Version: 0.9.9.7

**Comment by RojjaCebolla** [comment]
sounds like a good pull request you could make, grepping for instances of difficulty name strings and replacing them

**Comment by epyon** [comment]
The long form names are traditional Doom names, and kinda need to be there. Unfortunately as opposed to Doom itself, the game needs to reference difficulty levels, and those long form names are really hard to use in confined space situations.
