### ISSUE TITLE
Strange sounds

### ISSUE THREAD

**Issue by Wuzzy2** [chaosforgeorg/doomrl#35]
Some sounds used in the game are a bit strange or outright wrong:

* If you pick up a knife or a similar melee weapon, or equip such a weapon, you hear a gun reload sound
* If you open a door in hell, it still makes a sliding door sound (but it's a wooden door sprite)
* If you throw a knife, it sounds like a missile

Version: 0.9.9.7 on GNU/Linux

**Comment by epyon** [comment]
This is due to keeping fully restricted to the OG Doom soundset.
