### ISSUE TITLE
Title screen shows wrong version number

### ISSUE THREAD

**Issue by Wuzzy2** [chaosforgeorg/doomrl#38]
On the title screen (the first screen after you launch the game), the version number is shown twice, but they don't agree.

In the center of the title screen it says "Doom Roguelike 0.9.9.7" which I believe is the correct version number.
But in the top left corner it is "DOOMRL VERSION 0.9.9.76". This seems like a typo.

Tested in DoomRL 0.9.9.7 (version number according to Arch Linux package).

**Comment by RojjaCebolla** [comment]
@Wuzzy2 are you sure you're not looking at a capital G? There's no "0.9.9.76" anywhere in the source files, however I found a 0.9.9.7G here: https://github.com/chaosforgeorg/doomrl/blob/7db8b01539156a99930a43a5c97dc5f3c3f56196/src/doommenuview.pas#L176

**Comment by Wuzzy2** [comment]
That might be true. It's a strange and small font.

Why is there a G anyway? What is the difference between 0.9.9.7G and 0.9.9.7?

**Comment by RojjaCebolla** [comment]
my best guess is that the G represents the move from local files that could no longer compile, to an updated toolchain and this github repo. or something like that.

**Comment by epyon** [comment]
The G means you're running the Graphical version.
