### ISSUE TITLE
Dotted lines across screen on OS X

### ISSUE THREAD

**Issue by aacohn84** [chaosforgeorg/doomrl#6]
On OS X 10.6.11, there are dotted lines across the screen. In windowed mode (800x600) they appear on the entire window. In full-screen, they reach the full height of the screen, but the lines appear to remain confined to 800px of width.

I e-mailed you about this already and learned that you will try to fix it after obtaining a newer Mac. I'm posting this issue in hopes that maybe someone in the community will be able to fix it.

![image](https://cloud.githubusercontent.com/assets/3269395/21084202/977ea538-bfb4-11e6-9975-f7912954d482.png)

**Comment by werediver** [comment]
I experience the same issue on OS X 10.11.6. It appears almost always, but sometimes DRL starts with clean screen. At the moment I can't figure out what conditions may impact this.

**Comment by singalen** [comment]
Seems to be gone with SDL_image from #4 on 10.13.

**Comment by epyon** [comment]
Should be fixed in development now, will confirm once I do a OSX build.
